### ISSUE TITLE
posting to AXL using the client + generated client for 11.5 not working

### ISSUE THREAD

**Issue by Randle-Lanre** [jamessantiago/UC.NET#1]
posting to the Api using the just exits the console application with exit code 0 and does not post to the AXL API

**Comment by jamessantiago** [comment]
The AXL API is setup for 10.5.  You'll need to setup a 11.5 client similar the ones already there.  See this question for more info on the AXL client setup:
https://stackoverflow.com/questions/35761583/wcf-maxes-cpu-when-waiting-on-transparantproxystub-crosscontext-function-during

**Comment by Randle-Lanre** [comment]
i followed the example and  generated a client for 11.5 https://github.com/Randle-Lanre/CiscoCliAXL,
tried to call it from program class (console class)

**Comment by jamessantiago** [comment]
Looks like it might be due to you calling the executeasync method instead of execute:
https://github.com/Randle-Lanre/CiscoCliAXL/blob/master/axTestConsole/Program.cs#L86

If you want to call executeasync you need to wait on the results by calling result or wait on the returning object before exiting your console app.

**Comment by Randle-Lanre** [comment]
Thanks @jamessantiago i would look into this and update this tomorrow morning (thanks again) :)

**Comment by Randle-Lanre** [comment]
@jamessantiago changing the ``executeAsync`` to ``execute`` didn't fix the issue, it just starts and stays for a few seconds and exit like a normal console program nothing gets update in CUCM

**Comment by jamessantiago** [comment]
Also note that running execute doesn't throw an exception.  You need to
check the results for the exception object and handle accordingly.  Check
out some of the tests to see how to handle exceptions and results:
https://github.com/jamessantiago/UC.NET/blob/master/UC.NET/UcClient_10_5.Tests/AxlClientTest.cs

With Regard,
James Santiago, PhD

**Comment by Randle-Lanre** [comment]
Thanks for the help, try/ catch not catching any exception https://github.com/Randle-Lanre/CiscoCliAXL/blob/73561c8f53fe6d5b0b33f9334bfe8b0ecbb6dc17/axTestConsole/Program.cs#L203


runs like it all worked ( no way to see request is successful (or not), i have tried Soap UI just to see if My was the one with the issue, but it goes smoothly, could it be because the project (one class library and console app) are in .net core ?

**Comment by Randle-Lanre** [comment]
Solved with the help of: https://stackoverflow.com/questions/62008806/unable-to-post-to-axl-endpoint/62100201#62100201

> SoapCore generates elements with default values when it can, e.g. nil for string elements. This causes a problem with <addUser>, as the <customerName> element should only be sent to CUCM
